### ISSUE TITLE
nanopi-m1-debian-sd4g-20170204.img HDMI only 720dpi?

### ISSUE THREAD

**Issue by RoyChin** [friendlyarm/h3_lichee#10]
nanopi-m1-debian-sd4g-20170204.img HDMI only 720dpi?

how cat to build HDMI 1080p?

**Comment by igorpecovnik** [comment]
https://github.com/igorpecovnik/lib
Debian or Ubuntu with all possible screen resolutions.

**Comment by RoyChin** [comment]
HDMI 1080p success.
change /home/roy/lichee/tools/pack/chips/sun8iw7p1/configs/nanopi-h3/boards
[boot_disp]
hdmi_mode = 10

./gen_script.sh -b nanopi-m1
./fuse_uboot.sh /dev/sdx
