### ISSUE TITLE
ERROR: build kernel Failed

### ISSUE THREAD

**Issue by samimash** [friendlyarm/h3_lichee#11]
I recently got a nanopi m1 and I am using [the official documentation ](http://wiki.friendlyarm.com/wiki/index.php/NanoPi_M1#Make_Your_Own_Debian)

I downloaded the lichee source code and this toolchain: `gcc-linaro-arm.tar.xz` as the documentation said, but when I try to compile the source code, I got this error:

    arm-linux-gnueabi-gcc: error trying to exec 'cc1': execvp: No such file or directory
    ERROR: build kernel Failed

i need to solve this,because i want to use the nanopi M1 in a specific application

I am running Ubuntu 17.04 and I am a beginner in both arm processor and Linux environment but I have a background in electronics

whole code:

        ./build.sh -p sun8iw7p1 -b nanopi-h3
    INFO: ----------------------------------------
    INFO: build lichee ...
    INFO: chip: sun8iw7p1
    INFO: platform: linux
    INFO: business: 
    INFO: kernel: linux-3.4
    INFO: board: nanopi-h3
    INFO: output: out/sun8iw7p1/linux/nanopi-h3
    INFO: ----------------------------------------
    INFO: build kernel ...
    INFO: prepare toolchain ...
    INFO: skip kernel clean for nanopi-h3 Linux system.
    Building kernel
    /home/sami/lichee/linux-3.4/output/lib/modules/3.4.39-h3
      CHK     include/linux/version.h
      CHK     include/generated/utsrelease.h
    make[1]: 'include/generated/mach-types.h' is up to date.
      CC      kernel/bounds.s
    arm-linux-gnueabi-gcc: error trying to exec 'cc1': execvp: No such file or directory
    /home/sami/lichee/linux-3.4/./Kbuild:35: recipe for target 'kernel/bounds.s' failed
    make[1]: *** [kernel/bounds.s] Error 1
    Makefile:986: recipe for target 'prepare0' failed
    make: *** [prepare0] Error 2
    make: *** Waiting for unfinished jobs....
      CC      scripts/mod/empty.o
    arm-linux-gnueabi-gcc: error trying to exec 'cc1': execvp: No such file or directory
    scripts/Makefile.build:307: recipe for target 'scripts/mod/empty.o' failed
    make[2]: *** [scripts/mod/empty.o] Error 1
    scripts/Makefile.build:443: recipe for target 'scripts/mod' failed
    make[1]: *** [scripts/mod] Error 2
    Makefile:507: recipe for target 'scripts' failed
    make: *** [scripts] Error 2
    ERROR: build kernel Failed
    INFO: use a fake rootfs.ext4.
    1+0 records in
    1+0 records out
    1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00234644 s, 447 MB/s
    mke2fs 1.43.4 (31-Jan-2017)
    
    Filesystem too small for a journal
    INFO: ----------------------------------------
    
    INFO: build sun8iw7p1 linux  lichee OK
    
    INFO: ----------------------------------------

**Comment by wuweidong0107** [comment]
refer to http://wiki.friendlyarm.com/wiki/index.php/NanoPi_M1. You missed the "Install Cross Compiler" section.

**Comment by samimash** [comment]
actually i did that already 
i downloaded the file and past it into the toolchain directory
is it possible that the file is broken?
how i can be sure

**Comment by wuweidong0107** [comment]
do this:
$ cd lichee
$ ls ./brandy/toolchain/gcc-arm/bin/arm-linux-gnueabi-gcc

**Comment by samimash** [comment]
ok friend i did it
i got this 
s```
ami@sami-HP-Pavilion-g6-Notebook-PC:~$ cd lichee
sami@sami-HP-Pavilion-g6-Notebook-PC:~/lichee$  ls ./brandy/toolchain/gcc-arm/bin/arm-linux-gnueabi-gcc
./brandy/toolchain/gcc-arm/bin/arm-linux-gnueabi-gcc
```
i tried to recompile after,and the same error show up

**Comment by wuweidong0107** [comment]
run this command:
$ cd lichee
$ ./brandy/toolchain/gcc-arm/bin/arm-linux-gnueabi-gcc -v
..
gcc version 4.6.3 20120201 (prerelease) (crosstool-NG linaro-1.13.1-2012.02-20120222 - Linaro GCC 2012.02)
check if you can get the gcc version

**Comment by samimash** [comment]
i ran the command
it return
`bash: ./brandy/toolchain/gcc-arm/bin/arm-linux-gnueabi-gcc : No such file or directory`
?

**Comment by samimash** [comment]
i solved the issue 
thanks for the help

**Comment by wuweidong0107** [comment]
Nice. How to ? 32bit PC ubuntu?

**Comment by samimash** [comment]
i was missing this part
`sudo apt-get install gawk git gnupg flex bison gperf build-essential \
zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev \
libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 \
libgl1-mesa-dev g++-multilib mingw32 tofrodos \
python-markdown libxml2-utils xsltproc zlib1g-dev:i386`
