### ISSUE TITLE
Wrong dvfs operation points

### ISSUE THREAD

**Issue by ThomasKaiser** [friendlyarm/h3_lichee#2]
One of our devs brought to my attention that your dvfs settings (I blindly copied) lead to wrong dvfs behaviour. The leading 0 has to be eliminated [here](https://github.com/friendlyarm/h3_lichee/blob/549685751433f51d698c838574f99aa6e20e8fe1/tools/pack/chips/sun8iw7p1/configs/nanopi-h3/sys_config.fex#L699).

Detailed explanation: https://github.com/igorpecovnik/lib/issues/284#issuecomment-216655399

**Comment by wuweidong0107** [comment]
Hello, Thomas. 

I've tried:
[dvfs_table]
pmuic_type = 1
pmu_gpio0         = port:PL06<1><1><2><1>
pmu_level0        = 11300
pmu_level1        = 1100
;extremity_freq = 1200000000
max_freq = 1200000000
min_freq = 480000000
boot_freq = 1200000000
LV_count = 4

LV1_freq = 1200000000
LV1_volt = 1300

LV2_freq = 1008000000
LV2_volt = 1300

LV3_freq = 816000000
LV3_volt = 1100

LV4_freq = 480000000
LV4_volt = 1100

I got result(without hdmi): 
cpu=0 online=1 temperature=48 governor=interactive cur_freq=480000              
cpu=1 online=1 temperature=48 governor=interactive cur_freq=480000              
cpu=2 online=1 temperature=48 governor=interactive cur_freq=480000              
cpu=3 online=1 temperature=48 governor=interactive cur_freq=480000

**Comment by ThomasKaiser** [comment]
Hmm... the temperature looks like the SoC is fed with 1.3V then. Do you really use a programmable voltage generator or not?

**Comment by wuweidong0107** [comment]
The multimeter shows 1.094v when cpu=0 online=1 temperature=48 governor=interactive cur_freq=480000...

**Comment by ThomasKaiser** [comment]
Is that Armbian or your OS image using u-boot from BSP sources? If the latter the temperature would make sense. For still unknown reasons the thermal readouts when using mainline u-boot (as Armbian does) are lower. We suspect it's some clock based stuff but at least it's a known 'problem' that Armbian shows lower temperatures than OS images using u-boot 2011.09.

**Comment by wuweidong0107** [comment]
Test Armbian:
cpu=0 online=1 temperature=52 governor=interactive cur_freq=240000
cpu=1 online=1 temperature=52 governor=interactive cur_freq=240000
cpu=2 online=1 temperature=52 governor=interactive cur_freq=240000
cpu=3 online=1 temperature=52 governor=interactive cur_freq=240000

$ uptime 
11:34:56 up 8 min,  1 user,  load average: 0.63, 0.24, 0.13

**Comment by ThomasKaiser** [comment]
BTW: We improved our THS settings a bit and I hope we also fixed board auto detection reliably in Armbian 5.13.

Can you please give [this OS image](http://kaiser-edv.de/tmp/4U4tkD/Armbian_5.13_Nanopim1_Debian_jessie_3.4.112_desktop.7z) a try and test it on NanoPi M1 with 512MB and 1GB and get back to me with feedback?
