### ISSUE TITLE
Compile for touchscreen.ko

### ISSUE THREAD

**Issue by LeePower** [friendlyarm/h3_lichee#3]
Hi, I'm trying to get my touchscreen to work in my Android
I've modified the line
`CONFIG_INPUT_TOUCHSCREEN = y`
in sun8iw7p1smp_android_defconfig
and run ./build.sh lunch
Everything compiled fine.
I was expecting to see a usbtouchscreen.ko in the output/lib/module/modules/3.4.39/ folder
But I can't find it, would anyone help me? Thanks!

**Comment by pccr10001** [comment]
An option will either indicate some driver **is built into the kernel ("=y")** or will **be built as a module ("=m")** or is not selected. The unselected state can either be indicated by a line starting with "#" (e.g. "# CONFIG_SCSI is not set") or by the absence of the relevant line from the .config file. 

So you will not see "touchscreen.ko" in int the modules directory.
You can type the following command to verify the drivers is working or not.
dmesg | grep touchscreen


Reference: http://www.tldp.org/HOWTO/SCSI-2.4-HOWTO/kconfig.html

**Comment by LeePower** [comment]
Thank you @pccr10001 well explained!
